# Generated by Django 4.0.4 on 2022-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_student',
            name='student',
        ),
        migrations.AddField(
            model_name='code_student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
